name: Deploy Porfolio

on:
  push:
    branches: [ "main" ]

jobs:         
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy .env file
        run: |
          cp .env.example .env
      
      - name: Add variables to .env
        run: |
          echo "APP_OWNER=${{ secrets.APP_OWNER }}" >> .env
      
      - name: Update variables to .env
        run: |
          sed -i "s/^APP_NAME=.*/APP_NAME=${{ secrets.APP_NAME }}/" .env

      - name: Deployment to Server via SSH
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username:  ${{ secrets.SSH_USER }}
          key:  ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/environment 
            git pull origin main