name: Deploy Porfolio

on:
  push:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy .env file
        run: |
          cp .env.example .env
      
      - name: Add variables to .env
        run: |
          echo "APP_OWNER=${{ secrets.APP_OWNER }}" >> .env
      
      - name: Update variables to .env
        run: |
          sed -i "s/^APP_NAME=.*/APP_NAME=${{ secrets.APP_NAME }}/" .env
          